name: Daily Print News Notifier

on:
  schedule:
    - cron: '0 23 * * *'  # 毎日8:00 JST（日本時間）に実行（UTC 23:00）
  workflow_dispatch:       # 手動実行も可能

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Python 3.11 をセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 必要なライブラリをインストール
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests

      - name: ニュース通知スクリプトを実行
        run: python print_news_full.py
